const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
const GET_VIDEOGAMES_BY_NAME = 'GET_VIDEOGAMES_BY_NAME';
const GET_VIDEOGAME_DETAIL = 'GET_VIDEOGAME_DETAIL';
const GET_GENRES = 'GET_GENRES';
const POST_VIDEOGAME = 'POST_VIDEOGAME';
const PUT_VIDEOGAME = 'PUT_VIDEOGAME';
const DELETE_VIDEOGAME = 'DELETE_VIDEOGAME';
const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
const FILTER_BY_CREATED = 'FILTER_BY_CREATED';
const FILTER_BY_API = 'FILTER_BY_API';
const ORDER_BY_NAME_ASC = 'ORDER_BY_NAME_ASC';
const ORDER_BY_NAME_DESC = 'ORDER_BY_NAME_DESC';
const ORDER_BY_RATING_ASC = 'ORDER_BY_RATING_ASC';
const ORDER_BY_RATING_DESC = 'ORDER_BY_RATING_DESC';

